# Generated by Django 3.0.4 on 2020-03-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassengerId', models.CharField(max_length=50)),
                ('Survived', models.IntegerField(blank=True, null=True)),
                ('Pclass', models.IntegerField(default=0)),
                ('Age', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Sex', models.CharField(max_length=6)),
                ('SibSp', models.IntegerField()),
                ('Parch', models.IntegerField()),
                ('Ticket', models.CharField(max_length=10)),
                ('Fare', models.CharField(max_length=10)),
                ('Cabin', models.CharField(blank=True, max_length=10, null=True)),
                ('Embarked', models.CharField(max_length=10)),
            ],
        ),
    ]
