# Generated by Django 3.0.4 on 2020-03-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0002_remove_titanic_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='titanic',
            name='Fare',
            field=models.FloatField(default=0),
        ),
    ]
